### ISSUE TITLE
Permit using '-' in target names in POSIX mode

### ISSUE THREAD

**Issue by illiliti** [rmyorston/pdpmake#17]
I value such strictness(I always write only posix makefiles), but disallowing using hyphen character in target names is too much.

POSIX states the following:
> Implementations may allow other characters in target names as extensions.

Please use this opportunity to permit using hyphen character in target names.

**Comment by illiliti** [comment]
Same thing with '/'

**Comment by rmyorston** [comment]
The standard is explicit about which characters are allowed in target names. '-' and '/' aren't included in the list and implementations aren't required to support them.

In my opinion pdpmake shouldn't allow the use of non-standard characters in target names in POSIX mode. It does allow them as an extension.

**Comment by samboy** [comment]
I agree that for this Makefile implementation, we should stick closely to the POSIX standard. The reason to have a POSIX `make` is so developers can fix their makefiles which violate POSIX. If you want `/` and `-` in a POSIX makefile, update the standard.

**Comment by illiliti** [comment]
And pdpmake follows POSIX! If pdpmake would implement this extension, it would still be within POSIX boundaries, since POSIX permit other characters as extension. It is explicitly defined in spec. Why not implement this extension and be sane?

**Comment by samboy** [comment]
POSIX make assumes the source and target are in the same directory. The workaround for strict POSIX compliance is to have the Makefile (which I call `Makefile.posix`) make symbolic links for source files in the target directory with the `Makefile.posix` rule set.

**Comment by samboy** [comment]
For the record, if one is willing to break POSIX, the fix is a trivial one-line change.

https://github.com/samboy/maramake/commit/dc4b4b7e614bbb0736856788516edad8f01bd4fb

(`maramake` is a fork of this code I have so that I can have a tiny make with `/` in targets, and without any GPL code)

The problem is this: There *might* exist, somewhere out there, possibly with something like QNX or VxWorks, a POSIX compliant `make` implementation which does not allow `/` in targets. Such an implementation would be perfectly compliant with POSIX standards. With the number of POSIX development environments hidden behind paywalls out there, we need to strictly follow POSIX to ensure our code will compile on any such system. 

It’s the same reason why we can’t use the commonly used and widely deployed `egrep` shortcut for `grep -E`. Since POSIX doesn’t mandate `egrep`, it might not be deployed on a given POSIX system. I should note here that POSIX *does* acknowledge the existence of egrep, but it’s not part of the POSIX standard *per se*. Also, `fgrep` is similarly non-POSIX.

**Comment by illiliti** [comment]
I just leave it here: https://www.austingroupbugs.net/view.php?id=1615

**Comment by samboy** [comment]
Excellent! Hopefully, this was just an oversight by the Open Group, and not because of some obscure real-world implementation of Make. It’s sad Joerg Schilling is no longer with us to let us know if some ancient SunOS version of `make` would have an issue with allowing `/` and `-` in target names.

**Comment by samboy** [comment]
The ticket has been accepted, so I think we can implement this while being 100% POSIX compliant. Again: https://www.austingroupbugs.net/view.php?id=1615

**Comment by xparq** [comment]
FTR, it got also "Applied" a few weeks afterwards! Yay. (It's in Draft 2.1)
