### ISSUE TITLE
Invalid "invalid macro assignment"?

### ISSUE THREAD

**Issue by xparq** [rmyorston/pdpmake#31]
I can't get enough of these lovely one-liners, but they shouldn't be "almost recognized" as macro assignments:

    debug:; @echo "a = $(a)"

or just:

    debug:; @echo a = $(a)

They trigger an `invalid macro assignment` error.
They are fine with anything else than a `=` (and its friends), or on their own line in a normal command block:

    debug:
	    @echo a = $(a)

_(Tried with BusyBox v1.37.0-FRP-5181-g5c1a3b00e.)_

**Comment by rmyorston** [comment]
Macro assignments were being detected before target rules. This didn't matter in the original code because inline commands on target rules weren't supported.

I've changed the order. The test suite still passes, but this is quite an intrusive change so caution is advised.

The busybox-w32 applet has also been updated and new prerelease binaries have been issued.

**Comment by xparq** [comment]
Thanks! I'm glad it could be resolved with simply flipping the order. (I was kinda secretly worried that it may have hidden tentacles of unexpected internal dependencies. Hopefully none. I've read the (original) code, but nothing stood out. Which means nothing, of course, but feels good to say. :) )

**Comment by xparq** [comment]
Shall I close this, or is it up to you?
